/* Autogenerated by png2wx.pl on Fri Aug  4 10:01:16 2017 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_vfkaps;
extern wxBitmap *_img_vfkaps_pi;

#ifdef VFKAPS_USE_SVG
extern wxString _svg_vfkaps;
extern wxString _svg_vfkaps_toggled;
#endif

#endif /* ICONS_H */
